# Generated by Django 2.1.7 on 2019-06-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='game_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.GamePlayer'),
        ),
    ]
