# Generated by Django 2.1.7 on 2019-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190627_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_started',
            field=models.BooleanField(default=False),
        ),
    ]
