# Generated by Django 2.1.7 on 2019-07-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0018_game_round_started")]

    operations = [
        migrations.RemoveField(model_name="message", name="game_player"),
        migrations.AddField(
            model_name="message",
            name="username",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
