# Generated by Django 2.1.7 on 2019-08-05 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("app", "0024_auto_20190707_2139")]

    operations = [
        migrations.AddField(
            model_name="gameplayer", name="id", field=models.BigIntegerField(default=1)
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="game_players",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
