# Generated by Django 2.1.7 on 2019-08-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0026_auto_20190806_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_players",
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
