# Generated by Django 2.1.7 on 2019-08-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0033_gameplayer_loser")]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="action_type",
            field=models.CharField(default="no_move", max_length=200),
        )
    ]
